services:
  - type: web
    name: rondelltvatten-api
    runtime: docker
    repo: https://github.com/PatrikLax/rondelltvatten
    region: frankfurt
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        value: 10000
